apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/firm-vertex-412814/users/staging
          name: users
          env:
            - name: APP_NAME
              value: User
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql
            #       key: DATABASE_URL