apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roles
  name: roles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roles
  template:
    metadata:
      labels:
        app: roles
    spec:
      containers:
        - image: europe-southwest1-docker.pkg.dev/firm-vertex-412814/roles/staging
          name: roles
          env:
            - name: APP_NAME
              value: Role
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql
            #       key: DATABASE_URL
          ports:
            - containerPort: 3002
