services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - db
      - redis
      - users
      - auth
      - roles

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vision
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  users:
    image: vision-users
    env_file:
      - ../apps/users/.env
    ports:
      - 3000:3000
    depends_on:
      - db

  auth:
    image: vision-auth
    env_file:
      - ../apps/auth/.env
    ports:
      - 3001:3001
    depends_on:
      - db
      - redis

  roles:
    image: vision-roles
    env_file:
      - ../apps/roles/.env
    ports:
      - 3002:3002
    depends_on:
      - db

volumes:
  redis:
    driver: local
